{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wildside.fullname" . }}-config
  labels:
    {{- include "wildside.labels" . | nindent 4 }}
data:
{{ range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value | toString }}"
{{- end }}
{{- end }}
