{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wildside.fullname" . }}-config
  labels:
    {{- include "wildside.labels" . | nindent 4 }}
data:
{{- range $key := keys .Values.config | sortAlpha }}
  {{ $key }}: "{{ index $.Values.config $key | toString }}"
{{- end }}
{{- end }}
