{{- if .Values.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wildside.fullname" . }}
  labels:
    {{- include "wildside.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: {{ include "wildside.fullname" . }}
    minReplicas: {{ .Values.autoscaling.minReplicas }}
    maxReplicas: {{ .Values.autoscaling.maxReplicas }}
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- $behavior := .Values.autoscaling.behavior }}
    {{- if or $behavior.scaleUp $behavior.scaleDown }}
    behavior:
      {{- with $behavior.scaleUp }}
      scaleUp:
        {{- with .stabilizationWindowSeconds }}
        stabilizationWindowSeconds: {{ . }}
        {{- end }}
        {{- with .selectPolicy }}
        selectPolicy: {{ . }}
        {{- end }}
        {{- with .policies }}
        policies:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with $behavior.scaleDown }}
      scaleDown:
        {{- with .stabilizationWindowSeconds }}
        stabilizationWindowSeconds: {{ . }}
        {{- end }}
        {{- with .selectPolicy }}
        selectPolicy: {{ . }}
        {{- end }}
        {{- with .policies }}
        policies:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
