{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wildside.fullname" . }}
spec:
{{- if ge (int .Values.replicaCount) 2 }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
{{- else }}
  minAvailable: 1
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wildside.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
