apiVersion: v1
kind: Service
metadata:
  name: {{ include "wildside.fullname" . }}
  labels:
    {{- include "wildside.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    {{- include "wildside.selectorLabels" . | nindent 4 }}
  ports:
    - name: {{ .Values.service.portName | default "http" }}
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
