apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wildside-app
  namespace: myapp
spec:
  interval: 5m
  chart:
    spec:
      # This points to your new chart directory
      chart: ./deploy/charts/wildside
      reconcileStrategy: Revision
      interval: 5m
      sourceRef:
        kind: GitRepository
        name: flux-system # Assumes your repo is the 'flux-system' source
        namespace: flux-system
  # Default values can be specified here, but we will use the chart's defaults
  values: {}
  install:
    remediation:
      retries: 3
    createNamespace: true
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    cleanupOnFail: true
    rollback:
      enable: true
