# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
spec/openapi.json:
  no-empty-servers:
    - '#/openapi'
  info-license-strict:
    - '#/info/license'
  operation-4xx-response:
    - '#/paths/~1health~1live/get/responses'
    - '#/paths/~1health~1ready/get/responses'
  security-defined:
    - '#/paths/~1api~1v1~1login/post'
    - '#/paths/~1api~1v1~1users/get'
    - '#/paths/~1health~1live/get'
    - '#/paths/~1health~1ready/get'
