# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
spec/openapi.json:
  no-empty-servers:
    - '#/servers'
      # owner: platform-engineering
      # rationale: Server URLs are injected per environment by Traefik; the spec intentionally leaves them blank.
      # review by: 2025-12-31
  operation-4xx-response:
    - '#/paths/~1health~1live/get/responses'
      # owner: platform-engineering
      # rationale: Health probes return 200 or 503 to reflect service state;
      #   4xx responses would signal client misconfiguration, not an API
      #   contract change.
      # review by: 2026-03-31
    - '#/paths/~1health~1ready/get/responses'
      # owner: platform-engineering
      # rationale: Health probes return 200 or 503 to reflect service state;
      #   4xx responses would signal client misconfiguration, not an API
      #   contract change.
      # review by: 2026-03-31
