# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
spec/openapi.json:
  operation-4xx-response:
    # owner: Platform Team
    # reason: Health endpoints intentionally omit error payloads; we only expose 200s to keep uptime probes trivial.
    # review by: 2025-06-30
    - '#/paths/~1health~1live/get/responses'
    - '#/paths/~1health~1ready/get/responses'
  security-defined:
    # owner: Platform Team
    # reason: Login remains intentionally unauthenticated, list-users lacks a
    #   formal cookie security scheme, and health checks stay public until
    #   zero-trust rollout lands.
    # review by: 2025-06-30
    - '#/paths/~1api~1v1~1login/post'
    - '#/paths/~1api~1v1~1users/get'
    - '#/paths/~1health~1live/get'
    - '#/paths/~1health~1ready/get'
