# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
spec/openapi.json:
  no-empty-servers:
    - '#/servers'
      # owner: platform-engineering
      # rationale: Server URLs are injected per environment by Traefik; the spec intentionally leaves them blank.
      # review by: 2025-12-31
