apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wildside-app
spec:
  values:
    replicaCount: 3
    image:
      tag: "v1.2.3" # Production image tag
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    ingress:
      hostname: "prod-api.wildside.cc"
    config:
      APP_ENV: "production"
