apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wildside-app
spec:
  values:
    replicaCount: 3
    pdb:
      enabled: true
      minAvailable: 2
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    autoscaling:
      enabled: false
    ingress:
      enabled: true
      hostname: "prod-api.wildside.cc"
      tlsSecretName: wildside-prod-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
