apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wildside-app
spec:
  values:
    replicaCount: 3
    pdb:
      minAvailable: 2
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
    container:
      livenessProbe:
        timeoutSeconds: 2
      readinessProbe:
        timeoutSeconds: 2
    ingress:
      hostname: "prod-api.wildside.cc"
      tls:
        enabled: true
        secretName: wildside-prod-tls
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    config:
      APP_ENV: "production"
