apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: api.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp-backend
            port: { number: 80 }
