apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-api-cert
  namespace: myapp
spec:
  secretName: myapp-api-tls  # This matches your Ingress tls.secretName
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 2160h        # 90d
  renewBefore: 360h      # 15d
  privateKey:
    rotationPolicy: Always
  dnsNames:
    - api.wildside.cc  # Matches your Ingress host
