apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
commonLabels:
  app: myapp-backend
  app.kubernetes.io/name: myapp-backend
  app.kubernetes.io/part-of: myapp
  app.kubernetes.io/component: backend
commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
resources:
  - deployment.yaml
  - service.yaml
  - pdb.yaml
configMapGenerator:
  - name: myapp-config
    literals:
      - APP_ENV=production
secretGenerator:
  - name: myapp-secrets
    envs:
      - secret.env
generatorOptions:
  disableNameSuffixHash: false
patchesStrategicMerge:
  - patches/deployment-security.yaml
  - patches/deployment-resources.yaml
  - patches/configmap-immutable.yaml
