apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp
commonLabels:
  app: myapp-backend
resources:
  - deployment.yaml
  - pdb.yaml
patches:
  - path: patches/deployment-security.yaml
    target:
      kind: Deployment
      name: myapp-backend
  - path: patches/deployment-resources.yaml
    target:
      kind: Deployment
      name: myapp-backend
