apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pdb.yaml
patchesStrategicMerge:
  - patches/deployment-security.yaml
  - patches/deployment-resources.yaml
