version: '3.9'
services:
  backend:
    build:
      context: ..
      dockerfile: deploy/docker/backend.Dockerfile
    ports: ["8080:8080"]
    environment:
      - RUST_LOG=info
  web:
    image: nginx:1.27-alpine
    volumes:
      - ../frontend-pwa/dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports: ["3000:80"]
