replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/acme/myapp-backend
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

pdb:
  enabled: true
  minAvailable: 1

service:
  type: ClusterIP
  portName: http
  port: 80
  targetPort: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: "traefik" # Default to controller
  hostname: "api.wildside.cc"
  tlsSecretName: "myapp-api-tls"
  annotations: {}

# Non-secret configuration. Keys become environment variables via a ConfigMap.
config:
  APP_ENV: "development"

# Reference an externally managed Secret; map environment variables to keys.
existingSecretName: ""
secretEnvFromKeys: {}

affinity: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault
  fsGroup: 1000

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

container:
  livenessProbe:
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /health/ready
      port: http
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
