replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/acme/myapp-backend
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

pdb:
  enabled: true
  minAvailable: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: "traefik" # Default to your new controller
  hostname: "api.wildside.cc"
  tlsSecretName: "myapp-api-tls"
  annotations: {}

# You can also include default env vars, secrets, etc.
config:
  APP_ENV: "development"
secretEnv: {}

affinity: {}

securityContext: {}

container:
  livenessProbe:
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /health/ready
      port: http
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
