replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/acme/myapp-backend
  tag: ""
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

pdb:
  enabled: true
  minAvailable: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: "traefik" # Default to controller
  hostname: "api.wildside.cc"
  tlsSecretName: "myapp-api-tls"
  annotations: {}

# You can also include default env vars, secrets, etc.
config:
  # Non-secret configuration only
  APP_ENV: "development"

# Map environment variables to keys in an existing Secret
existingSecretName: ""
secretEnvFromKeys: {}

affinity: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

container:
  livenessProbe:
    httpGet:
      path: /health/live
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /health/ready
      port: http
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  startupProbe:
    httpGet:
      path: /health/ready
      port: http
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12
