[package]
name = "rstest-bdd"
version = "0.1.0-alpha4"
edition = "2024"
description = "Minimal rstest-bdd shim for behavioural-style attributes on stable Rust"
license = "ISC"

[lib]
proc-macro = true
