//! PostgreSQL-backed `UserRepository` implementation using Diesel ORM.
//!
//! This adapter implements the domain's `UserRepository` port, translating
//! between domain `User` entities and Diesel row structs. All database
//! operations are async via `diesel-async`.
//!
//! # Error Handling
//!
//! All Diesel and pool errors are mapped to the domain's `UserPersistenceError`
//! variants using the constructor helpers generated by `define_port_error!`.

use async_trait::async_trait;
use diesel::prelude::*;
use diesel::upsert::excluded;
use diesel_async::RunQueryDsl;
use tracing::debug;

use pagination::Direction;

use crate::domain::ports::{ListUsersPageRequest, UserPersistenceError, UserRepository};
use crate::domain::{DisplayName, User, UserCursorKey, UserId};

use super::models::{NewUserRow, UserRow};
use super::pool::{DbPool, PoolError};
use super::schema::users;

/// Diesel-backed implementation of the `UserRepository` port.
///
/// This adapter provides PostgreSQL persistence for `User` entities using
/// Diesel ORM with async support. It requires a configured `DbPool` for
/// connection management.
///
/// # Example
///
/// ```ignore
/// let pool = DbPool::new(config).await?;
/// let repo = DieselUserRepository::new(pool);
///
/// let user = User::try_from_strings("uuid-here", "Display Name")?;
/// repo.upsert(&user).await?;
/// ```
#[derive(Clone)]
pub struct DieselUserRepository {
    pool: DbPool,
}

impl DieselUserRepository {
    /// Create a new repository with the given connection pool.
    pub fn new(pool: DbPool) -> Self {
        Self { pool }
    }
}

/// Map pool errors to domain persistence errors.
fn map_pool_error(error: PoolError) -> UserPersistenceError {
    match error {
        PoolError::Checkout { message } | PoolError::Build { message } => {
            UserPersistenceError::connection(message)
        }
    }
}

/// Map Diesel errors to domain persistence errors.
fn map_diesel_error(error: diesel::result::Error) -> UserPersistenceError {
    use diesel::result::{DatabaseErrorKind, Error as DieselError};

    match &error {
        DieselError::DatabaseError(kind, info) => {
            debug!(?kind, message = info.message(), "diesel operation failed");
        }
        _ => debug!(
            error_type = %std::any::type_name_of_val(&error),
            "diesel operation failed"
        ),
    }

    match error {
        DieselError::NotFound => UserPersistenceError::query("record not found"),
        DieselError::QueryBuilderError(_) => UserPersistenceError::query("database query error"),
        DieselError::DatabaseError(kind, _) => match kind {
            DatabaseErrorKind::UniqueViolation => {
                UserPersistenceError::query("unique constraint violation")
            }
            DatabaseErrorKind::ForeignKeyViolation => {
                UserPersistenceError::query("foreign key violation")
            }
            DatabaseErrorKind::NotNullViolation => {
                UserPersistenceError::query("not null violation")
            }
            DatabaseErrorKind::CheckViolation => {
                UserPersistenceError::query("check constraint violation")
            }
            DatabaseErrorKind::SerializationFailure => {
                UserPersistenceError::query("serialization failure")
            }
            DatabaseErrorKind::ReadOnlyTransaction => {
                UserPersistenceError::query("read-only transaction")
            }
            DatabaseErrorKind::ClosedConnection => {
                UserPersistenceError::connection("database connection error")
            }
            _ => UserPersistenceError::query("database error"),
        },
        _ => UserPersistenceError::query("database error"),
    }
}

/// Convert a database row to a domain User.
///
/// # Errors
///
/// Returns `UserPersistenceError::Query` if the row data fails domain validation
/// (e.g., display name constraints).
fn row_to_user(row: UserRow) -> Result<User, UserPersistenceError> {
    let user_id = UserId::from_uuid(row.id);
    let display_name = DisplayName::new(row.display_name).map_err(|err| {
        debug!(?err, "invalid display name loaded from database");
        UserPersistenceError::query("invalid user record")
    })?;
    Ok(User::new(user_id, display_name, row.created_at))
}

fn row_to_users(rows: Vec<UserRow>) -> Result<Vec<User>, UserPersistenceError> {
    rows.into_iter().map(row_to_user).collect()
}

fn fetch_limit(limit: usize) -> Result<i64, UserPersistenceError> {
    let with_overflow_row = limit
        .checked_add(1)
        .ok_or_else(|| UserPersistenceError::query("page limit overflow"))?;
    i64::try_from(with_overflow_row)
        .map_err(|_| UserPersistenceError::query("page limit exceeds database range"))
}

#[async_trait]
impl UserRepository for DieselUserRepository {
    async fn upsert(&self, user: &User) -> Result<(), UserPersistenceError> {
        let mut conn = self.pool.get().await.map_err(map_pool_error)?;

        let new_user = NewUserRow {
            id: *user.id().as_uuid(),
            display_name: user.display_name().as_ref(),
            created_at: user.created_at(),
        };

        diesel::insert_into(users::table)
            .values(&new_user)
            .on_conflict(users::id)
            .do_update()
            .set(users::display_name.eq(excluded(users::display_name)))
            .execute(&mut conn)
            .await
            .map(|_| ())
            .map_err(map_diesel_error)
    }

    async fn find_by_id(&self, id: &UserId) -> Result<Option<User>, UserPersistenceError> {
        let mut conn = self.pool.get().await.map_err(map_pool_error)?;

        let result: Option<UserRow> = users::table
            .filter(users::id.eq(id.as_uuid()))
            .select(UserRow::as_select())
            .first(&mut conn)
            .await
            .optional()
            .map_err(map_diesel_error)?;

        match result {
            Some(row) => row_to_user(row).map(Some),
            None => Ok(None),
        }
    }

    async fn list_page(
        &self,
        request: ListUsersPageRequest,
    ) -> Result<Vec<User>, UserPersistenceError> {
        let mut conn = self.pool.get().await.map_err(map_pool_error)?;
        let (cursor, limit) = request.into_parts();
        let fetch_limit = fetch_limit(limit)?;

        let rows = match cursor {
            None => users::table
                .order((users::created_at.asc(), users::id.asc()))
                .limit(fetch_limit)
                .select(UserRow::as_select())
                .load(&mut conn)
                .await
                .map_err(map_diesel_error)?,
            Some(cursor) => {
                let (key, direction) = cursor.into_parts();
                match direction {
                    Direction::Next => list_page_after(&mut conn, key, fetch_limit).await?,
                    Direction::Prev => list_page_before(&mut conn, key, fetch_limit).await?,
                }
            }
        };

        row_to_users(rows)
    }
}

async fn list_page_after(
    conn: &mut diesel_async::AsyncPgConnection,
    key: UserCursorKey,
    fetch_limit: i64,
) -> Result<Vec<UserRow>, UserPersistenceError> {
    users::table
        .filter(
            users::created_at.gt(key.created_at).or(users::created_at
                .eq(key.created_at)
                .and(users::id.gt(key.id))),
        )
        .order((users::created_at.asc(), users::id.asc()))
        .limit(fetch_limit)
        .select(UserRow::as_select())
        .load(conn)
        .await
        .map_err(map_diesel_error)
}

async fn list_page_before(
    conn: &mut diesel_async::AsyncPgConnection,
    key: UserCursorKey,
    fetch_limit: i64,
) -> Result<Vec<UserRow>, UserPersistenceError> {
    let mut rows = users::table
        .filter(
            users::created_at.lt(key.created_at).or(users::created_at
                .eq(key.created_at)
                .and(users::id.lt(key.id))),
        )
        .order((users::created_at.desc(), users::id.desc()))
        .limit(fetch_limit)
        .select(UserRow::as_select())
        .load(conn)
        .await
        .map_err(map_diesel_error)?;
    rows.reverse();
    Ok(rows)
}

#[cfg(test)]
mod tests {
    //! Regression coverage for this module.
    use super::*;
    use rstest::rstest;

    #[rstest]
    fn pool_error_maps_to_connection_error() {
        let pool_err = PoolError::checkout("connection refused");
        let persistence_err = map_pool_error(pool_err);

        assert!(matches!(
            persistence_err,
            UserPersistenceError::Connection { .. }
        ));
        assert!(
            persistence_err.to_string().contains("connection refused"),
            "preserve useful diagnostics"
        );
    }

    #[rstest]
    fn diesel_error_maps_to_query_error() {
        let diesel_err = diesel::result::Error::NotFound;
        let persistence_err = map_diesel_error(diesel_err);

        assert!(matches!(
            persistence_err,
            UserPersistenceError::Query { .. }
        ));
        assert!(
            persistence_err.to_string().contains("record not found"),
            "preserve stable, user-facing diagnostics"
        );
    }
}
