classDiagram
    class Values {
      +int replicaCount
      +Image image
      +Resources resources
      +Service service
      +Pdb pdb
      +Ingress ingress
      +Config config
      +string existingSecretName
      +SecretEnvFromKeys secretEnvFromKeys
      +string nameOverride
      +string fullnameOverride
      +PodSecurityContext podSecurityContext
      +SecurityContext securityContext
      +Autoscaling autoscaling
      +Affinity affinity
      +Container container
    }
    class Image {
      +string repository
      +string tag
      +string pullPolicy
    }
    class Resources {
      +Requests requests
      +Limits limits
    }
    class Requests {
      +string cpu
      +string memory
    }
    class Limits {
      +string cpu
      +string memory
    }
    class Service {
      +string type
      +string portName
      +int port
      +string targetPort
    }
    class Pdb {
      +bool enabled
      +int minAvailable
    }
    class Autoscaling {
      +bool enabled
      +int minReplicas
      +int maxReplicas
      +int targetCPUUtilizationPercentage
    }
    class Affinity {
      +map<string, any> podAntiAffinity
    }
    class Ingress {
      +bool enabled
      +string className
      +string hostname
      +string tlsSecretName
      +map<string,string> annotations
    }
    class Config {
      +string APP_ENV
    }
    class SecretEnvFromKeys {
      +map<string,string> envToKey
    }
    class PodSecurityContext {
      +SeccompProfile seccompProfile
      +int fsGroup
    }
    class SeccompProfile {
      +string type
    }
    class SecurityContext {
      +bool runAsNonRoot
      +int runAsUser
      +bool allowPrivilegeEscalation
      +bool readOnlyRootFilesystem
    }
    class Container {
      +Probe livenessProbe
      +Probe readinessProbe
      +Probe startupProbe
    }
    class Probe {
      +int timeoutSeconds
    }
    Values --> Image
    Values --> Resources
    Resources --> Requests
    Resources --> Limits
    Values --> Service
    Values --> Pdb
    Values --> Ingress
    Values --> Config
    Values --> SecretEnvFromKeys
    Values --> PodSecurityContext
    Values --> SecurityContext
    Values --> Autoscaling
    Values --> Affinity
    Values --> Container
    PodSecurityContext --> SeccompProfile
    Container --> Probe
