name: wildside-infra-k8s
description: >-
  Provision a DigitalOcean Kubernetes cluster and render platform fixtures for
  GitOps deployment. This action provisions the cluster via OpenTofu, renders
  Flux-ready manifests for all platform modules, and commits them to the GitOps
  repository for FluxCD reconciliation.
author: Wildside platform team
branding:
  icon: cloud
  color: blue

inputs:
  cluster_name:
    description: Name of the Kubernetes cluster to provision.
    required: true
  environment:
    description: Logical environment identifier (e.g. preview, staging, production).
    required: true
  region:
    description: DigitalOcean region for the cluster (e.g. lon1, nyc3).
    required: true
  kubernetes_version:
    description: >-
      DOKS Kubernetes version. When omitted, uses the latest available version
      for the region.
    required: false
  node_pools:
    description: >-
      JSON-encoded array of node pool configurations. Each pool should specify
      name, size, count, and optional labels/taints.
    required: false
  domain:
    description: Root DNS domain for cluster services (e.g. example.com).
    required: true
  acme_email:
    description: Email address for ACME certificate registration.
    required: true
  gitops_repository:
    description: >-
      Target GitOps repository in owner/repo format (e.g. wildside-dev/wildside-infra).
    required: true
  gitops_branch:
    description: Branch in the GitOps repository to commit manifests to.
    required: false
    default: main
  gitops_token:
    description: >-
      GitHub token with write access to the GitOps repository. Should have
      contents:write permission.
    required: true
  vault_address:
    description: HTTPS endpoint of the Vault appliance for secrets management.
    required: false
  vault_role_id:
    description: AppRole role_id for Vault authentication.
    required: false
  vault_secret_id:
    description: AppRole secret_id for Vault authentication.
    required: false
  vault_ca_certificate:
    description: >-
      PEM-encoded CA certificate for Vault TLS verification. Optional when Vault
      serves a publicly trusted certificate.
    required: false
  digitalocean_token:
    description: DigitalOcean API token for cluster provisioning.
    required: true
  spaces_access_key:
    description: DigitalOcean Spaces access key for OpenTofu state backend.
    required: true
  spaces_secret_key:
    description: DigitalOcean Spaces secret key for OpenTofu state backend.
    required: true
  cloudflare_api_token_secret_name:
    description: >-
      Name of the Kubernetes Secret containing the Cloudflare API token for DNS
      management.
    required: false
    default: cloudflare-api-token
  enable_traefik:
    description: Deploy Traefik ingress controller.
    required: false
    default: "true"
  enable_cert_manager:
    description: Deploy cert-manager for TLS certificate management.
    required: false
    default: "true"
  enable_external_dns:
    description: Deploy ExternalDNS for automatic DNS record management.
    required: false
    default: "true"
  enable_vault_eso:
    description: Deploy Vault + External Secrets Operator integration.
    required: false
    default: "true"
  enable_cnpg:
    description: Deploy CloudNativePG for PostgreSQL databases.
    required: false
    default: "true"
  dry_run:
    description: >-
      When true, run tofu plan without applying and skip GitOps commit. Useful
      for validating changes before deployment.
    required: false
    default: "false"
  opentofu_version:
    description: Version of OpenTofu to install.
    required: false
    default: "1.8.3"

outputs:
  cluster_name:
    description: Name of the provisioned cluster.
    value: ${{ steps.publish.outputs.cluster_name }}
  cluster_id:
    description: DigitalOcean cluster ID.
    value: ${{ steps.publish.outputs.cluster_id }}
  cluster_endpoint:
    description: Kubernetes API server endpoint.
    value: ${{ steps.publish.outputs.cluster_endpoint }}
  gitops_commit_sha:
    description: Commit SHA of the GitOps repository update (empty in dry-run mode).
    value: ${{ steps.publish.outputs.gitops_commit_sha }}
  rendered_manifest_count:
    description: Number of manifests rendered for the cluster.
    value: ${{ steps.publish.outputs.rendered_manifest_count }}

runs:
  using: composite
  steps:
    - name: Install uv
      id: install-uv
      uses: astral-sh/setup-uv@557e51de59eb14aaaba2ed9621916900a91d50c6

    - name: Install OpenTofu
      id: install-opentofu
      uses: opentofu/setup-opentofu@592200bd325f72c94421f5a8e5dd77252cecc48c
      with:
        tofu_version: ${{ inputs.opentofu_version }}
        tofu_wrapper: false

    - name: Install doctl
      id: install-doctl
      uses: digitalocean/action-doctl@135ac0aa0eed4437d547c6f12c364d3006b42824
      with:
        token: ${{ inputs.digitalocean_token }}

    - name: Prepare inputs
      id: prepare
      shell: bash
      env:
        INPUT_CLUSTER_NAME: ${{ inputs.cluster_name }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_REGION: ${{ inputs.region }}
        INPUT_KUBERNETES_VERSION: ${{ inputs.kubernetes_version }}
        INPUT_NODE_POOLS: ${{ inputs.node_pools }}
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_ACME_EMAIL: ${{ inputs.acme_email }}
        INPUT_GITOPS_REPOSITORY: ${{ inputs.gitops_repository }}
        INPUT_GITOPS_BRANCH: ${{ inputs.gitops_branch }}
        INPUT_GITOPS_TOKEN: ${{ inputs.gitops_token }}
        INPUT_VAULT_ADDRESS: ${{ inputs.vault_address }}
        INPUT_VAULT_ROLE_ID: ${{ inputs.vault_role_id }}
        INPUT_VAULT_SECRET_ID: ${{ inputs.vault_secret_id }}
        INPUT_VAULT_CA_CERTIFICATE: ${{ inputs.vault_ca_certificate }}
        INPUT_DIGITALOCEAN_TOKEN: ${{ inputs.digitalocean_token }}
        INPUT_SPACES_ACCESS_KEY: ${{ inputs.spaces_access_key }}
        INPUT_SPACES_SECRET_KEY: ${{ inputs.spaces_secret_key }}
        INPUT_CLOUDFLARE_API_TOKEN_SECRET_NAME: ${{ inputs.cloudflare_api_token_secret_name }}
        INPUT_ENABLE_TRAEFIK: ${{ inputs.enable_traefik }}
        INPUT_ENABLE_CERT_MANAGER: ${{ inputs.enable_cert_manager }}
        INPUT_ENABLE_EXTERNAL_DNS: ${{ inputs.enable_external_dns }}
        INPUT_ENABLE_VAULT_ESO: ${{ inputs.enable_vault_eso }}
        INPUT_ENABLE_CNPG: ${{ inputs.enable_cnpg }}
        INPUT_DRY_RUN: ${{ inputs.dry_run }}
        UV_CACHE_DIR: ${{ runner.temp }}/uv-cache
      run: uv run scripts/prepare_infra_k8s_inputs.py

    - name: Provision cluster
      id: provision
      shell: bash
      env:
        DIGITALOCEAN_TOKEN: ${{ env.DIGITALOCEAN_TOKEN }}
        SPACES_ACCESS_KEY: ${{ env.SPACES_ACCESS_KEY }}
        SPACES_SECRET_KEY: ${{ env.SPACES_SECRET_KEY }}
        UV_CACHE_DIR: ${{ runner.temp }}/uv-cache
      run: uv run scripts/provision_cluster.py

    - name: Render platform manifests
      id: render
      shell: bash
      env:
        UV_CACHE_DIR: ${{ runner.temp }}/uv-cache
      run: uv run scripts/render_platform_manifests.py

    - name: Commit to GitOps repository
      id: commit
      if: ${{ !contains(fromJSON('["true","True","TRUE","1","yes","Yes","YES"]'), inputs.dry_run) }}
      shell: bash
      env:
        UV_CACHE_DIR: ${{ runner.temp }}/uv-cache
      run: uv run scripts/commit_gitops_manifests.py

    - name: Publish outputs
      id: publish
      shell: bash
      env:
        UV_CACHE_DIR: ${{ runner.temp }}/uv-cache
      run: uv run scripts/publish_infra_k8s_outputs.py
